### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by kwanzapili** [mate-desktop/mate-control-center#664]
#### Expected behaviour
launch mate-control-center application

#### Actual behaviour
Always crashes before doing anything. This is a persistent problem that carries over from all prior versions of mate that I have used. In other words, I have never seen mate-control-center working. The error it emits is:

```
**
libslab:ERROR:app-shell.c:1327:application_launcher_compare: code should not be reached
Bail out! libslab:ERROR:app-shell.c:1327:application_launcher_compare: code should not be reached
Aborted (core dumped)

```
See the backtrace below:
```
(gdb) bt
#0  0x00007ffff64a5971 in raise () from /lib64/libc.so.6
#1  0x00007ffff648fa52 in abort () from /lib64/libc.so.6
#2  0x00007ffff685013c in ?? () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff68ad38b in g_assertion_message_expr () from /usr/lib64/libglib-2.0.so.0
#4  0x00007ffff7bc10e0 in ?? () from /usr/lib64/libmate-slab.so.0
#5  0x00007ffff687fe78 in ?? () from /usr/lib64/libglib-2.0.so.0
#6  0x00007ffff7bc0d34 in ?? () from /usr/lib64/libmate-slab.so.0
#7  0x00007ffff7bc0e7e in ?? () from /usr/lib64/libmate-slab.so.0
#8  0x00007ffff7bc2112 in generate_categories () from /usr/lib64/libmate-slab.so.0
#9  0x000055555555596c in activate (app=0x55555576f0f0) at control-center.c:134
#10 0x00007ffff6b77bbf in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff6b897b6 in ?? () from /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff6b8fc41 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#13 0x00007ffff6b901b2 in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#14 0x00007ffff6e9c4c8 in ?? () from /usr/lib64/libgio-2.0.so.0
#15 0x00007ffff6e9c61e in g_application_run () from /usr/lib64/libgio-2.0.so.0
#16 0x0000555555555748 in main (argc=<optimized out>, argv=<optimized out>) at control-center.c:185
```

#### Steps to reproduce the behaviour
Simply type "mate-control-center"

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
OpenSuSE **but I compiled this particular code from source not the distribution version**.

**Comment by lukefromdc** [comment]
This looks like something is missing from your install "code could not be reached"

**Comment by kwanzapili** [comment]
I cannot think of what code could possibly be missing. The application compiles successfully with my current setup. So I imagine it would flag any missing code whilst it was building? Or if did not find something, it would not call it later? Actually, I have never known to work even with earlier versions, 1.18 onwards to 1.26. However, I can use the subitems such as _mate-appearance-properties_, etc. That makes me think the problem is specific to this app rather to the items it might call. Does it not simply call these subitems?

**Comment by lukefromdc** [comment]
Not on launch it does not. The "capplets" as the subapplications are called
are called from and by the running instance of mate-control-center or can 
be invoked directly from terminal
