### ISSUE TITLE
mate-keybinding-properties segfault

### ISSUE THREAD

**Issue by lenik** [mate-desktop/mate-control-center#80]
mate-control-center: 1.6.0-3.1+7.wheezy

Can't startup. The backtrace:

```
#0  __strcmp_ssse3 () at ../sysdeps/i386/i686/multiarch/strcmp-ssse3.S:228
#1  0xb718512b in g_strcmp0 (
    str1=0x812ea40 "org.mate.control-center.keybinding", 
    str2=0x6e616863 <Address 0x6e616863 out of bounds>)
    at /build/glib2.0-Ot8bbC/glib2.0-2.36.4/./glib/gtestutils.c:2028
#2  0x0804d9a3 in key_match (model=0x80de360, path=0x8124918, iter=0xbfffeea0, 
    data=0xbfffef70) at mate-keybinding-properties.c:459
#3  0xb7b5e741 in ?? () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#4  0xb7b5e706 in ?? () from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#5  0xb7b5f8bb in gtk_tree_model_foreach ()
   from /usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
#6  0x08050189 in key_is_already_shown (entry=0x812c550, model=0x80de360)
    at mate-keybinding-properties.c:477
#7  append_keys_to_tree (builder=builder@entry=0x806cea0, 
    title=<optimized out>, 
    schema=schema@entry=0x80541f0 "org.mate.control-center.keybinding", 
    package=0x0, package@entry=0x8089bb0 "\200\271\022\b", 
    keys_list=keys_list@entry=0x812c528) at mate-keybinding-properties.c:620
#8  0x08050ca7 in append_keys_to_tree_from_gsettings (builder=0x806cea0, 
    gsettings_path=<optimized out>) at mate-keybinding-properties.c:1028
#9  reload_key_entries (builder=builder@entry=0x806cea0)
    at mate-keybinding-properties.c:1084
#10 0x0804d505 in setup_dialog (marco_settings=0x80c6cc8, builder=0x806cea0)
---Type <return> to continue, or q <return> to quit---
    at mate-keybinding-properties.c:1904
#11 main (argc=1, argv=0xbffff144) at mate-keybinding-properties.c:1963
```

**Comment by HuangZhiquan** [comment]
this patch is not enough to deal with all, when you change the order of getting from settings and getting from file, the question is still here, but i find that before you append key(KeyListEntry) to entries, initializating all member, it will work fine. in fact, if you want to use a pointer, you need to initializate it to NULL.
